import PageLabel from "@/components/(client)/PageLabel/PageLabel";
import type { Metadata } from "next";
import styles from './Layout.module.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <PageLabel />
        </header>
        <nav className={styles.nav}>
          <a href="/register">Register</a>
          <a href="/login">Login</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
